export const divisionsPerCountries = [
  { id: "1", divisions: 5, name: "USA" },
  { id: "2", divisions: 4, name: "Argentina" },
  { id: "3", divisions: 4, name: "Brasil" },
  { id: "4", divisions: 4, name: "Canada" },
  { id: "5", divisions: 5, name: "China" },
  { id: "6", divisions: 4, name: "Türkiye" },
  { id: "7", divisions: 5, name: "España" },
  { id: "8", divisions: 4, name: "Deutschland" },
  { id: "9", divisions: 3, name: "Sverige" },
  { id: "10", divisions: 5, name: "Italia" },
  { id: "11", divisions: 5, name: "France" },
  { id: "12", divisions: 5, name: "Hellas" },
  { id: "13", divisions: 4, name: "Belgium" },
  { id: "14", divisions: 4, name: "England" },
  { id: "15", divisions: 4, name: "Israel" },
  { id: "16", divisions: 3, name: "Nederland" },
  { id: "17", divisions: 4, name: "Australia" },
  { id: "18", divisions: 4, name: "Portugal" },
  { id: "19", divisions: 4, name: "Rossiya" },
  { id: "20", divisions: 5, name: "Lietuva" },
  { id: "21", divisions: 3, name: "Chile" },
  { id: "22", divisions: 3, name: "Colombia" },
  { id: "24", divisions: 4, name: "Hrvatska" },
  { id: "26", divisions: 3, name: "Norge" },
  { id: "27", divisions: 3, name: "Österreich" },
  { id: "28", divisions: 3, name: "Schweiz" },
  { id: "29", divisions: 4, name: "Srbija" },
  { id: "30", divisions: 3, name: "México" },
  { id: "33", divisions: 3, name: "Ukraina" },
  { id: "35", divisions: 4, name: "Bosna i Hercegovina" },
  { id: "36", divisions: 3, name: "Bulgaria" },
  { id: "37", divisions: 4, name: "Česká Rep." },
  { id: "39", divisions: 3, name: "Danmark" },
  { id: "41", divisions: 4, name: "Eesti" },
  { id: "43", divisions: 3, name: "Indonesia" },
  { id: "44", divisions: 3, name: "Ireland" },
  { id: "45", divisions: 4, name: "Hong Kong" },
  { id: "46", divisions: 4, name: "Latvija" },
  { id: "48", divisions: 4, name: "Magyarország" },
  { id: "49", divisions: 3, name: "Makedonija" },
  { id: "50", divisions: 3, name: "Malaysia" },
  { id: "56", divisions: 3, name: "Perú" },
  { id: "57", divisions: 4, name: "Pilipinas" },
  { id: "58", divisions: 5, name: "Polska" },
  { id: "59", divisions: 3, name: "Iran" },
  { id: "61", divisions: 3, name: "România" },
  { id: "62", divisions: 3, name: "Sakartvelo" },
  { id: "65", divisions: 3, name: "Singapore" },
  { id: "66", divisions: 4, name: "Slovenija" },
  { id: "67", divisions: 3, name: "Slovensko" },
  { id: "69", divisions: 4, name: "Suomi" },
  { id: "70", divisions: 4, name: "Taiwan" },
  { id: "73", divisions: 4, name: "Uruguay" },
  { id: "74", divisions: 3, name: "Venezuela" },
  { id: "76", divisions: 3, name: "Crna Gora" },
  { id: "77", divisions: 3, name: "Cyprus" },
  { id: "85", divisions: 3, name: "Belarus" },
  { id: "99", divisions: 4, name: "Utopia" },
  { id: "100", divisions: 2, name: "Nations of Africa" },
  { id: "101", divisions: 3, name: "Nations of Europe" },
  { id: "102", divisions: 3, name: "Nations of Asia" },
  { id: "103", divisions: 3, name: "Nations of America" },
];
